In [11]:
import pandas as pd
import numpy as np
import itertools
import os
from scipy.io import wavfile
import librosa
import librosa.display

import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df_summary = pd.read_csv(".\Data\processedResults\summaryTable.csv", index_col = 0)
demo_df = pd.read_csv(".\Data\VideoDemographics.csv")

In [24]:
df_summary.head()

,FileName,VoiceVote,VoiceLevel,FaceVote,FaceLevel,MultiModalVote,MultiModalLevel
1,1001_IEO_NEU_XX,N,69.1,N,92.22,N,64.78
2,1001_IEO_HAP_LO,N,71.67,H,57,H,57.38
3,1001_IEO_HAP_MD,N,67.71,H,62.62,H,56.56
4,1001_IEO_HAP_HI,H,63.5,H,68.25,H,73.2
5,1001_IEO_SAD_LO,N,73.71,N,73.5,N,74.8

In [25]:
demo_df.head()

   ActorID  Age     Sex              Race     Ethnicity
0     1001   51    Male         Caucasian  Not Hispanic
1     1002   21  Female         Caucasian  Not Hispanic
2     1003   21  Female         Caucasian  Not Hispanic
3     1004   42  Female         Caucasian  Not Hispanic
4     1005   29    Male  African American  Not Hispanic

In [26]:
Crema = "./Data/AudioWAV/"

In [30]:
crema_directory_list = os.listdir(Crema)

file_emotion = []
file_path = []
actor_id = []

for file in crema_directory_list:
    # storing file paths
    file_path.append(Crema + file)
    # storing file emotions
    part=file.split('_')
    file_emotion.append(part[2])
    actor_id.append(int(part[0][-4:]))

#Construct Dataframe
emotion_df = pd.DataFrame(file_emotion, columns=['Emotion'])
path_df = pd.DataFrame(file_path, columns=['Path'])
actor_df = pd.DataFrame(actor_id, columns = ["ActorID"])
temp_df = pd.concat([actor_df,emotion_df, path_df], axis=1)

crema_df = temp_df.merge(demo_df, on = "ActorID")
crema_df.head()

,ActorID,Emotion,Path,Age,Sex,Race,Ethnicity
0,1001,ANG,./Data/AudioWAV/1001_DFA_ANG_XX.wav,51,Male,Caucasian,Not Hispanic
1,1001,DIS,./Data/AudioWAV/1001_DFA_DIS_XX.wav,51,Male,Caucasian,Not Hispanic
2,1001,FEA,./Data/AudioWAV/1001_DFA_FEA_XX.wav,51,Male,Caucasian,Not Hispanic
3,1001,HAP,./Data/AudioWAV/1001_DFA_HAP_XX.wav,51,Male,Caucasian,Not Hispanic
4,1001,NEU,./Data/AudioWAV/1001_DFA_NEU_XX.wav,51,Male,Caucasian,Not Hispanic